apiVersion: v2
name: castopod
description: Helm chart for Castopod - free and open-source hosting platform for podcasters.
type: application
version:
- 1.2.0
- 1.2.1
- 1.2.2
- 1.2.3
- 1.2.4
- 1.3.0
- 1.3.1
- 1.3.2
- 1.3.3
- 1.3.4
- 1.3.5
- 1.4.0
- 1.4.1
- 1.4.2
- 1.4.3
- 1.4.4
- 1.4.5
- 1.4.6
- 1.4.7
- 1.5.0
- 1.5.1
- 1.5.2
- 1.6.0
- 1.6.1
- 1.6.2
- 1.6.3
- 1.6.4
- 1.6.5
- 1.7.0
- 1.7.1
- 1.7.2
- 1.7.3
- 1.7.4
- 1.8.0
- 1.8.1
- 1.8.2
- 1.9.0
- 1.10.0
- 1.10.1
- 1.10.2
- 1.10.3
- 1.10.4
- 1.10.5
- 1.11.0
- 1.12.0
- 1.12.1
- 1.12.2
- 1.12.3
- 1.12.4
- 1.12.5
appVersion: "\"['1.2.0', '1.2.1', '1.2.2', '1.2.3', '1.2.4', '1.3.0', '1.3.1', '1.3.2',\
  \ '1.3.3', '1.3.4', '1.3.5', '1.4.0', '1.4.1', '1.4.2', '1.4.3', '1.4.4', '1.4.5',\
  \ '1.4.6', '1.4.7', '1.5.0', '1.5.1', '1.5.2', '1.6.0', '1.6.1', '1.6.2', '1.6.3',\
  \ '1.6.4', '1.6.5', '1.7.0', '1.7.1', '1.7.2', '1.7.3', '1.7.4', '1.8.0', '1.8.1',\
  \ '1.8.2', '1.9.0', '1.10.0', '1.10.1', '1.10.2', '1.10.3', '1.10.4', '1.10.5',\
  \ '1.11.0', '1.12.0', '1.12.1', '1.12.2', '1.12.3', '1.12.4', '1.12.5']\""
keywords:
- castopod
- storage
- http
- web
- php
maintainers:
- name: hiimluck3r
  email: luck3rinc@yandex.ru
  url: https://github.com/hiimluck3r
icon: https://raw.githubusercontent.com/hiimluck3r/helm-charts/master/etc/icons/castopod-logo.jpg
home: https://castopod.org/
sources:
- https://github.com/hiimluck3r/helm-charts/castopod
dependencies:
- name: mariadb
  version: 18.2.0
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: mariadb.enabled
- name: redis
  version: 19.5.0
  repository: oci://registry-1.docker.io/bitnamicharts
  condition: redis.enabled
