apiVersion: v2
name: castopod
description: Helm chart for Castopod - free and open-source hosting platform for podcasters.
type: application
version: 0.1.0
appVersion: "1.11.0"
keywords:
  - castopod
  - storage
  - http
  - web
  - php
maintainers:
  - name: hiimluck3r
    email: luck3rinc@yandex.ru
    url: https://github.com/hiimluck3r
dependencies:
  - name: mariadb
    version: 18.2.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: mariadb.enabled
  - name: redis
    version: 19.5.0
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: redis.enabled