{{- if or (gt .Values.replicaCount 1.0) (.Values.autoscaling.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "littlelink-server.fullname" . }}
  labels:
    {{- include "littlelink-server.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "littlelink-server.selectorLabels" . | nindent 6 }}
{{- end }}
