{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ default "castopod" .Values.secrets.name }}
  labels:
    {{- include "castopod.labels" . | nindent 4 }}
data:
  redis-password: {{ default "changemeredis" .Values.secrets.redis.password | b64enc | quote }}
  mariadb-password: {{ default "changememaria" .Values.secrets.mariadb.password | b64enc | quote }}
  mariadb-root-password: {{ default "changememaria" .Values.secrets.mariadb.password | b64enc | quote }}
  mariadb-replication-password: {{ default "changememaria" .Values.secrets.mariadb.password | b64enc | quote }}
{{- end }}