name: Update README.md for charts

on:
  - pull_request
    

jobs:
  updater:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.ref }}
    
    - name: Run helm-docs
      uses: losisin/helm-docs-github-action@v1
      with:
        chart-search-root: ./charts
        git-push: 'true'

    

